version: '3'

services:

  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./rasaengine:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/"]
      interval: 30s
      timeout: 10s
      retries: 5

  train:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./rasaengine:/app
    entrypoint: "rasa"
    command:
      - train
    depends_on:
      rasa:
        condition: service_healthy


  action-server:
    image: rasa/rasa-sdk:3.6.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./rasaengine/actions:/app/actions
    
   
    